[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
via_ir = true

[rpc_endpoints]
moderato = "https://rpc.moderato.tempo.xyz"

[etherscan]
moderato = { key = "", chain = 42431 }
